name: "iPerf3 SpeedTest Server"
description: "Home Assistant iPerf3 server for testing LAN and WiFi network performance."
version: "1.0.0"
slug: "iperf3_server"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5201/tcp: 5201
  5201/udp: 5201
ports_description:
  5201/tcp: "iPerf3 Server TCP Port"
  5201/udp: "iPerf3 Server UDP Port"
